package org.esa.beam.meris.icol.landsat.common;

/**
 * This interface is a container for constants specific for LANDSAT-products.
 *
 * @author Olaf Danne
 * @version $Revision: 8078 $ $Date: 2010-01-22 17:24:28 +0100 (Fr, 22 Jan 2010) $
 */
public interface LandsatConstants {

    String LANDSAT_DOWNSCALED_PRODUCT_TYPE_PREFIX = "L1G";
    String LANDSAT5_PRODUCT_TYPE_PREFIX = "LANDSAT5_TM";
    String LANDSAT7_PRODUCT_TYPE_PREFIX = "LANDSAT7_ETM+";

    String LANDSAT5_RADIANCE_1_BAND_NAME = "radiance_1";
    String LANDSAT5_RADIANCE_2_BAND_NAME = "radiance_2";
    String LANDSAT5_RADIANCE_3_BAND_NAME = "radiance_3";
    String LANDSAT5_RADIANCE_4_BAND_NAME = "radiance_4";
    String LANDSAT5_RADIANCE_5_BAND_NAME = "radiance_5";
    String LANDSAT5_RADIANCE_6_BAND_NAME = "radiance_6";
    String LANDSAT5_RADIANCE_7_BAND_NAME = "radiance_7";
    String LANDSAT7_RADIANCE_8_BAND_NAME = "radiance_8";

    int LANDSAT_RADIANCE_1_BAND_INDEX = 0;
    int LANDSAT_RADIANCE_2_BAND_INDEX = 1;
    int LANDSAT_RADIANCE_3_BAND_INDEX = 2;
    int LANDSAT_RADIANCE_4_BAND_INDEX = 3;
    int LANDSAT_RADIANCE_5_BAND_INDEX = 4;
    int LANDSAT5_RADIANCE_6_BAND_INDEX = 5;
    int LANDSAT5_RADIANCE_7_BAND_INDEX = 6;

    int LANDSAT7_RADIANCE_61_BAND_INDEX = 5;
    int LANDSAT7_RADIANCE_62_BAND_INDEX = 6;
    int LANDSAT7_RADIANCE_7_BAND_INDEX = 7;
    int LANDSAT7_RADIANCE_8_BAND_INDEX = 8;

    String LANDSAT7_RADIANCE_61_BAND_SUFFIX = "61";
    String LANDSAT7_RADIANCE_62_BAND_SUFFIX = "62";

    int LANDSAT5_FR_ORIG = 30;
    int LANDSAT_GEOM_FR = 300;
    int LANDSAT5_GEOM_RR = 1200;

    int OUTPUT_PRODUCT_TYPE_DOWNSCALE = 0;
    int OUTPUT_PRODUCT_TYPE_AECORR = 1;
    int OUTPUT_PRODUCT_TYPE_UPSCALE = 2;
    int OUTPUT_PRODUCT_TYPE_FLAGS = 3;

    String LANDSAT_CTP_BAND_NAME = "ctp";

    /**
     * The effective wavelengths (ICOL+ ATBD D4, table 1)
     */
    float[] LANDSAT5_SPECTRAL_BAND_EFFECTIVE_WAVELENGTHS = {
            478.37f,
            560.58f,
            660.75f,
            831.47f,
            1643.73f,
            11450.0f,
            2225.20f
    };

    float[] LANDSAT7_SPECTRAL_BAND_EFFECTIVE_WAVELENGTHS = {
            478.37f,
            560.58f,
            660.75f,
            831.47f,
            1643.73f,
            11450.0f,
            11450.0f,
            2225.20f,
            730.0f  // center of the panchromatic
    };

    /**
     * The names of the Landsat5 TM spectral band names.
     */
    String[] LANDSAT5_RADIANCE_BAND_NAMES = {
            LANDSAT5_RADIANCE_1_BAND_NAME, // 0
            LANDSAT5_RADIANCE_2_BAND_NAME, // 1
            LANDSAT5_RADIANCE_3_BAND_NAME, // 2
            LANDSAT5_RADIANCE_4_BAND_NAME, // 3
            LANDSAT5_RADIANCE_5_BAND_NAME, // 4
            LANDSAT5_RADIANCE_6_BAND_NAME, // 5
            LANDSAT5_RADIANCE_7_BAND_NAME, // 6
    };

    String[] LANDSAT7_RADIANCE_BAND_NAMES = {
            LANDSAT5_RADIANCE_1_BAND_NAME,
            LANDSAT5_RADIANCE_2_BAND_NAME,
            LANDSAT5_RADIANCE_3_BAND_NAME,
            LANDSAT5_RADIANCE_4_BAND_NAME,
            LANDSAT5_RADIANCE_5_BAND_NAME,
            LANDSAT5_RADIANCE_6_BAND_NAME + "1",
            LANDSAT5_RADIANCE_6_BAND_NAME + "2",
            LANDSAT5_RADIANCE_7_BAND_NAME,
            LANDSAT7_RADIANCE_8_BAND_NAME,
    };


    String LANDSAT_RADIANCE_BAND_PREFIX = "radiance";
    String LANDSAT_REFLECTANCE_BAND_PREFIX = "rho_toa";

    String LANDSAT_REFLECTANCE_1_BAND_NAME = LANDSAT_REFLECTANCE_BAND_PREFIX + "_tm1";
    String LANDSAT_REFLECTANCE_2_BAND_NAME = LANDSAT_REFLECTANCE_BAND_PREFIX + "_tm2";
    String LANDSAT_REFLECTANCE_3_BAND_NAME = LANDSAT_REFLECTANCE_BAND_PREFIX + "_tm3";
    String LANDSAT_REFLECTANCE_4_BAND_NAME = LANDSAT_REFLECTANCE_BAND_PREFIX + "_tm4";
    String LANDSAT_REFLECTANCE_5_BAND_NAME = LANDSAT_REFLECTANCE_BAND_PREFIX + "_tm5";
    String LANDSAT_REFLECTANCE_7_BAND_NAME = LANDSAT_REFLECTANCE_BAND_PREFIX + "_tm7";

    String LANDSAT5_REFLECTANCE_6_BAND_NAME = LANDSAT_REFLECTANCE_BAND_PREFIX + "_tm6";
    String LANDSAT7_REFLECTANCE_6a_BAND_NAME = LANDSAT_REFLECTANCE_BAND_PREFIX + "_tm61";
    String LANDSAT7_REFLECTANCE_6b_BAND_NAME = LANDSAT_REFLECTANCE_BAND_PREFIX + "_tm62";
    String LANDSAT7_REFLECTANCE_8_BAND_NAME = LANDSAT_REFLECTANCE_BAND_PREFIX + "_tm8";

    /**
     * The names of the Meris Level 1 spectral band names.
     */
    String[] LANDSAT5_REFLECTANCE_BAND_NAMES = {
            LANDSAT_REFLECTANCE_1_BAND_NAME, // 0
            LANDSAT_REFLECTANCE_2_BAND_NAME, // 1
            LANDSAT_REFLECTANCE_3_BAND_NAME, // 2
            LANDSAT_REFLECTANCE_4_BAND_NAME, // 3
            LANDSAT_REFLECTANCE_5_BAND_NAME, // 4
            LANDSAT5_REFLECTANCE_6_BAND_NAME, // 5
            LANDSAT_REFLECTANCE_7_BAND_NAME, // 6
    };

    String[] LANDSAT7_REFLECTANCE_BAND_NAMES = {
            LANDSAT_REFLECTANCE_1_BAND_NAME, // 0
            LANDSAT_REFLECTANCE_2_BAND_NAME, // 1
            LANDSAT_REFLECTANCE_3_BAND_NAME, // 2
            LANDSAT_REFLECTANCE_4_BAND_NAME, // 3
            LANDSAT_REFLECTANCE_5_BAND_NAME, // 4
            LANDSAT7_REFLECTANCE_6a_BAND_NAME, // 5
            LANDSAT7_REFLECTANCE_6b_BAND_NAME, // 6
            LANDSAT_REFLECTANCE_7_BAND_NAME, // 7
            LANDSAT7_REFLECTANCE_8_BAND_NAME, // 8
    };

    int LANDSAT5_NUM_SPECTRAL_BANDS = LANDSAT5_RADIANCE_BAND_NAMES.length;
    int LANDSAT7_NUM_SPECTRAL_BANDS = LANDSAT7_RADIANCE_BAND_NAMES.length;

    String LANDSAT_GAS_TRANSMITTANCE_BAND_PREFIX = "gas_transmittance";

    String LANDSAT_GAS_TRANSMITTANCE_1_BAND_NAME = LANDSAT_GAS_TRANSMITTANCE_BAND_PREFIX + "_tm1";
    String LANDSAT_GAS_TRANSMITTANCE_2_BAND_NAME = LANDSAT_GAS_TRANSMITTANCE_BAND_PREFIX + "_tm2";
    String LANDSAT_GAS_TRANSMITTANCE_3_BAND_NAME = LANDSAT_GAS_TRANSMITTANCE_BAND_PREFIX + "_tm3";
    String LANDSAT_GAS_TRANSMITTANCE_4_BAND_NAME = LANDSAT_GAS_TRANSMITTANCE_BAND_PREFIX + "_tm4";
    String LANDSAT_GAS_TRANSMITTANCE_5_BAND_NAME = LANDSAT_GAS_TRANSMITTANCE_BAND_PREFIX + "_tm5";
    String LANDSAT_GAS_TRANSMITTANCE_7_BAND_NAME = LANDSAT_GAS_TRANSMITTANCE_BAND_PREFIX + "_tm7";

    String LANDSAT5_GAS_TRANSMITTANCE_6_BAND_NAME = LANDSAT_GAS_TRANSMITTANCE_BAND_PREFIX + "_tm6";
    String LANDSAT7_GAS_TRANSMITTANCE_6a_BAND_NAME = LANDSAT_GAS_TRANSMITTANCE_BAND_PREFIX  + "_tm61";
    String LANDSAT7_GAS_TRANSMITTANCE_6b_BAND_NAME = LANDSAT_GAS_TRANSMITTANCE_BAND_PREFIX  + "_tm62";
    String LANDSAT7_GAS_TRANSMITTANCE_8_BAND_NAME = LANDSAT_GAS_TRANSMITTANCE_BAND_PREFIX  + "_tm8";

    /**
     * The names of the gaseous transmittance spectral band names.
     */
    String[] LANDSAT5_GAS_TRANSMITTANCE_BAND_NAMES = {
            LANDSAT_GAS_TRANSMITTANCE_1_BAND_NAME, // 0
            LANDSAT_GAS_TRANSMITTANCE_2_BAND_NAME, // 1
            LANDSAT_GAS_TRANSMITTANCE_3_BAND_NAME, // 2
            LANDSAT_GAS_TRANSMITTANCE_4_BAND_NAME, // 3
            LANDSAT_GAS_TRANSMITTANCE_5_BAND_NAME, // 4
            LANDSAT5_GAS_TRANSMITTANCE_6_BAND_NAME, // 5
            LANDSAT_GAS_TRANSMITTANCE_7_BAND_NAME, // 6
    };
    String[] LANDSAT7_GAS_TRANSMITTANCE_BAND_NAMES = {
            LANDSAT_GAS_TRANSMITTANCE_1_BAND_NAME, // 0
            LANDSAT_GAS_TRANSMITTANCE_2_BAND_NAME, // 1
            LANDSAT_GAS_TRANSMITTANCE_3_BAND_NAME, // 2
            LANDSAT_GAS_TRANSMITTANCE_4_BAND_NAME, // 3
            LANDSAT_GAS_TRANSMITTANCE_5_BAND_NAME, // 4
            LANDSAT7_GAS_TRANSMITTANCE_6a_BAND_NAME, // 5
            LANDSAT7_GAS_TRANSMITTANCE_6b_BAND_NAME, // 6
            LANDSAT_GAS_TRANSMITTANCE_7_BAND_NAME, // 7
            LANDSAT7_GAS_TRANSMITTANCE_8_BAND_NAME, // 8
    };


    String LANDSAT_RAYLEIGH_SCATT_BAND_PREFIX = "rayleigh_scatt";

    String LANDSAT_RAYLEIGH_SCATT_1_BAND_NAME = LANDSAT_RAYLEIGH_SCATT_BAND_PREFIX + "_tm1";
    String LANDSAT_RAYLEIGH_SCATT_2_BAND_NAME = LANDSAT_RAYLEIGH_SCATT_BAND_PREFIX + "_tm2";
    String LANDSAT_RAYLEIGH_SCATT_3_BAND_NAME = LANDSAT_RAYLEIGH_SCATT_BAND_PREFIX + "_tm3";
    String LANDSAT_RAYLEIGH_SCATT_4_BAND_NAME = LANDSAT_RAYLEIGH_SCATT_BAND_PREFIX + "_tm4";
    String LANDSAT_RAYLEIGH_SCATT_5_BAND_NAME = LANDSAT_RAYLEIGH_SCATT_BAND_PREFIX + "_tm5";
    String LANDSAT_RAYLEIGH_SCATT_7_BAND_NAME = LANDSAT_RAYLEIGH_SCATT_BAND_PREFIX + "_tm7";

    String LANDSAT5_RAYLEIGH_SCATT_6_BAND_NAME = LANDSAT_RAYLEIGH_SCATT_BAND_PREFIX + "_tm6";
    String LANDSAT7_RAYLEIGH_SCATT_6a_BAND_NAME = LANDSAT_RAYLEIGH_SCATT_BAND_PREFIX  + "_tm61";
    String LANDSAT7_RAYLEIGH_SCATT_6b_BAND_NAME = LANDSAT_RAYLEIGH_SCATT_BAND_PREFIX  + "_tm62";
    String LANDSAT7_RAYLEIGH_SCATT_8_BAND_NAME = LANDSAT_RAYLEIGH_SCATT_BAND_PREFIX  + "_tm8";


    /**
     * The names of the Rayleigh scattering spectral band names.
     */
    String[] LANDSAT5_RAYLEIGH_SCATT_BAND_NAMES = {
            LANDSAT_RAYLEIGH_SCATT_1_BAND_NAME, // 0
            LANDSAT_RAYLEIGH_SCATT_2_BAND_NAME, // 1
            LANDSAT_RAYLEIGH_SCATT_3_BAND_NAME, // 2
            LANDSAT_RAYLEIGH_SCATT_4_BAND_NAME, // 3
            LANDSAT_RAYLEIGH_SCATT_5_BAND_NAME, // 4
            LANDSAT5_RAYLEIGH_SCATT_6_BAND_NAME, // 5
            LANDSAT_RAYLEIGH_SCATT_7_BAND_NAME, // 6
    };
    String[] LANDSAT7_RAYLEIGH_SCATT_BAND_NAMES = {
            LANDSAT_RAYLEIGH_SCATT_1_BAND_NAME, // 0
            LANDSAT_RAYLEIGH_SCATT_2_BAND_NAME, // 1
            LANDSAT_RAYLEIGH_SCATT_3_BAND_NAME, // 2
            LANDSAT_RAYLEIGH_SCATT_4_BAND_NAME, // 3
            LANDSAT_RAYLEIGH_SCATT_5_BAND_NAME, // 4
            LANDSAT7_RAYLEIGH_SCATT_6a_BAND_NAME, // 5
            LANDSAT7_RAYLEIGH_SCATT_6b_BAND_NAME, // 6
            LANDSAT_RAYLEIGH_SCATT_7_BAND_NAME, // 7
            LANDSAT7_RAYLEIGH_SCATT_8_BAND_NAME, // 8
    };

    String LANDSAT_AEROSOL_SCATT_BAND_PREFIX = "aerosol_scatt";

    String LANDSAT_AEROSOL_SCATT_1_BAND_NAME = LANDSAT_AEROSOL_SCATT_BAND_PREFIX + "_tm1";
    String LANDSAT_AEROSOL_SCATT_2_BAND_NAME = LANDSAT_AEROSOL_SCATT_BAND_PREFIX + "_tm2";
    String LANDSAT_AEROSOL_SCATT_3_BAND_NAME = LANDSAT_AEROSOL_SCATT_BAND_PREFIX + "_tm3";
    String LANDSAT_AEROSOL_SCATT_4_BAND_NAME = LANDSAT_AEROSOL_SCATT_BAND_PREFIX + "_tm4";
    String LANDSAT_AEROSOL_SCATT_5_BAND_NAME = LANDSAT_AEROSOL_SCATT_BAND_PREFIX + "_tm5";
    String LANDSAT_AEROSOL_SCATT_7_BAND_NAME = LANDSAT_AEROSOL_SCATT_BAND_PREFIX + "_tm7";

    String LANDSAT5_AEROSOL_SCATT_6_BAND_NAME = LANDSAT_AEROSOL_SCATT_BAND_PREFIX + "_tm6";
    String LANDSAT7_AEROSOL_SCATT_6a_BAND_NAME = LANDSAT_AEROSOL_SCATT_BAND_PREFIX + "_tm61";
    String LANDSAT7_AEROSOL_SCATT_6b_BAND_NAME = LANDSAT_AEROSOL_SCATT_BAND_PREFIX + "_tm62";
    String LANDSAT7_AEROSOL_SCATT_8_BAND_NAME = LANDSAT_AEROSOL_SCATT_BAND_PREFIX + "_tm8";

    /**
     * The names of the aerosol scattering spectral band names.
     */
    String[] LANDSAT5_AEROSOL_SCATT_BAND_NAMES = {
            LANDSAT_AEROSOL_SCATT_1_BAND_NAME, // 0
            LANDSAT_AEROSOL_SCATT_2_BAND_NAME, // 1
            LANDSAT_AEROSOL_SCATT_3_BAND_NAME, // 2
            LANDSAT_AEROSOL_SCATT_4_BAND_NAME, // 3
            LANDSAT_AEROSOL_SCATT_5_BAND_NAME, // 4
            LANDSAT5_AEROSOL_SCATT_6_BAND_NAME, // 5
            LANDSAT_AEROSOL_SCATT_7_BAND_NAME, // 6
    };

    String[] LANDSAT7_AEROSOL_SCATT_BAND_NAMES = {
            LANDSAT_AEROSOL_SCATT_1_BAND_NAME, // 0
            LANDSAT_AEROSOL_SCATT_2_BAND_NAME, // 1
            LANDSAT_AEROSOL_SCATT_3_BAND_NAME, // 2
            LANDSAT_AEROSOL_SCATT_4_BAND_NAME, // 3
            LANDSAT_AEROSOL_SCATT_5_BAND_NAME, // 4
            LANDSAT7_AEROSOL_SCATT_6a_BAND_NAME, // 5
            LANDSAT7_AEROSOL_SCATT_6b_BAND_NAME, // 6
            LANDSAT_AEROSOL_SCATT_7_BAND_NAME, // 7
            LANDSAT7_AEROSOL_SCATT_8_BAND_NAME, // 8
    };

    float[] LANDSAT5_SOLAR_IRRADIANCES = {  // official USGC values, see also ICOL_D4, table 2
            1997.0f,
            1812.0f,
            1533.0f,
            1039.0f,
            230.8f,
            0.0f, // dummy
            84.9f
    };
    float[] LANDSAT7_SOLAR_IRRADIANCES = {  // official USGC values, see also ICOL_D4, table 2
            1997.0f,
            1812.0f,
            1533.0f,
            1039.0f,
            230.8f,
            0.0f, // dummy
            0.0f, // dummy
            84.9f,
            1533.0f // TBD for panchromatic band, use band 3 value for the moment
    };

    double SUN_EARTH_DISTANCE_SQUARE  = 2.240237947541881E22; // this is from current MERIS L2 Auxdata

    String LAND_FLAGS_SUMMER = "Summer";
    String LAND_FLAGS_WINTER = "Winter";

    double CTP_K_FACTOR = 15.0;  // in hPa/K . This is about 0.65K/100m. TBD!!

    double DEFAULT_OZONE_CONTENT = 0.32;
    double DEFAULT_SURFACE_PRESSURE = 1013.25;
    double DEFAULT_SURFACE_TM_APPARENT_TEMPERATURE = 300.0;
    double DEFAULT_BRIGHTNESS_THRESHOLD = 0.3;
    double DEFAULT_NDVI_CLOUD_THRESHOLD = 0.2;
    double DEFAULT_NDVI_LAND_THRESHOLD = 0.1;
    double DEFAULT_NDSI_THRESHOLD = 3.0;
    double DEFAULT_TM6_LAND_THRESHOLD = 300.0;
    double DEFAULT_TM6_CLOUD_THRESHOLD = 300.0;



    float[] LANDSAT5_NOMINAL_RAYLEIGH_OPTICAL_THICKNESS = {  // ICOL_D4, table 1
            0.17962f,
            0.09588f,
            0.04858f,
            0.01986f,
            0.00128f,
            0.0f, // dummy
            0.00038f
    };
    float[] LANDSAT7_NOMINAL_RAYLEIGH_OPTICAL_THICKNESS = {  // ICOL_D4, table 1
            0.17962f,
            0.09588f,
            0.04858f,
            0.01986f,
            0.00128f,
            0.0f, // dummy
            0.0f, // dummy
            0.00038f,
            0.04858f // TBD for panchromatic band, use band 3 value for the moment
    };


    float[] LANDSAT5_O3_OPTICAL_THICKNESS = {  // ICOL_D4, table 1
            0.0065f,
            0.00319f,
            0.00183f,
            0.0003f,
            0.0f,
            0.0f, // dummy
            0.0f
    };
    float[] LANDSAT7_O3_OPTICAL_THICKNESS = {  // ICOL_D4, table 1
            0.0065f,
            0.00319f,
            0.00183f,
            0.0003f,
            0.0f,
            0.0f, // dummy
            0.0f, // dummy
            0.0f,
            0.00183f // TBD for panchromatic band, use band 3 value for the moment
    };

}
